### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by vyaspranjal33** [vyaspranjal33/privacy-brigade#1]
Calling awesome Volunteers to Write about Privacy brigade In your own thoughts

**Comment by dhdutoit** [comment]
Hi @vyaspranjal33 , I would be willing to help. How and where can I get started? :)

**Comment by vyaspranjal33** [comment]
@dhdutoit  thanks 4 showing up interests please look at contributing.md file & try to make it more standard

**Comment by dhdutoit** [comment]
Cool, will have a look.

**Comment by dhdutoit** [comment]
@vyaspranjal33 , I created a PR. Hope it helps. :)

**Comment by vyaspranjal33** [comment]
good work @dhdutoit  looking forward more contributions

**Comment by vyaspranjal33** [comment]
@dhdutoit  can you make a website for privacy brigade
