### ISSUE TITLE
privacy talk

### ISSUE THREAD

**Issue by vyaspranjal33** [vyaspranjal33/privacy-brigade#4]
Host a Privacy session AT school/colleges 

- comment here to host a talk
- participants should deliver a talk online OR offline[this will help participants to improve Public speaking skills and confidence

**Comment by vyaspranjal33** [comment]
@princiya Here are photos from talk 
![image](https://user-images.githubusercontent.com/11768143/39877558-dd3750be-5493-11e8-944a-4de717c2cd53.png)

![image](https://user-images.githubusercontent.com/11768143/39877631-0de64c88-5494-11e8-8f63-74fb642074fd.png)

![image](https://user-images.githubusercontent.com/11768143/39878005-f28072a6-5494-11e8-8772-a9fed0173e2f.png)

**Comment by princiya** [comment]
Brilliant! 🎉
