### ISSUE TITLE
Design posters/ flyers

### ISSUE THREAD

**Issue by vyaspranjal33** [vyaspranjal33/privacy-brigade#5]
designing poster / flyer that helps people to understand

- Importance of privacy
- tips to achieve/maintain Privacy

**Comment by himankpathak** [comment]
Hi @vyaspranjal33, I would like to help you out with designs.
Any specific idea the poster should be bout?

**Comment by vyaspranjal33** [comment]
Hi @himankpathak  Thanks for showing Interest Something like this will be great 
![image](https://user-images.githubusercontent.com/11768143/39907966-75d01ee4-5509-11e8-94fc-c14f6eba3fd7.png)
